# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Documents/Project/radiation_detection_pynq/constraints/pynq_z2.xdc

# Block Designs: bd/radiation_system/radiation_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radiation_system || ORIG_REF_NAME==radiation_system} -quiet] -quiet

# IP: bd/radiation_system/ip/radiation_system_processing_system7_0_0/radiation_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radiation_system_processing_system7_0_0 || ORIG_REF_NAME==radiation_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/radiation_system/ip/radiation_system_auto_pc_0/radiation_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radiation_system_auto_pc_0 || ORIG_REF_NAME==radiation_system_auto_pc_0} -quiet] -quiet

# IP: bd/radiation_system/ip/radiation_system_axi_interconnect_0_0/radiation_system_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radiation_system_axi_interconnect_0_0 || ORIG_REF_NAME==radiation_system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/radiation_system/ip/radiation_system_axi_gpio_0_0/radiation_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radiation_system_axi_gpio_0_0 || ORIG_REF_NAME==radiation_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/radiation_system/ip/radiation_system_radiation_detector_0_0/radiation_system_radiation_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radiation_system_radiation_detector_0_0 || ORIG_REF_NAME==radiation_system_radiation_detector_0_0} -quiet] -quiet

# XDC: d:/Documents/Project/radiation_detection_pynq/radiation_detector/radiation_detector.gen/sources_1/bd/radiation_system/radiation_system_ooc.xdc
