# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Documents/Project/radiation_detection_pynq/radiation_detector/radiation_detector.srcs/sources_1/bd/radiation_system/ip/radiation_system_axi_gpio_0_0/radiation_system_axi_gpio_0_0.xci
# IP: The module: 'radiation_system_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Project/radiation_detection_pynq/radiation_detector/radiation_detector.gen/sources_1/bd/radiation_system/ip/radiation_system_axi_gpio_0_0/radiation_system_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'radiation_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/Project/radiation_detection_pynq/radiation_detector/radiation_detector.gen/sources_1/bd/radiation_system/ip/radiation_system_axi_gpio_0_0/radiation_system_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'radiation_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/Project/radiation_detection_pynq/radiation_detector/radiation_detector.gen/sources_1/bd/radiation_system/ip/radiation_system_axi_gpio_0_0/radiation_system_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'radiation_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Documents/Project/radiation_detection_pynq/radiation_detector/radiation_detector.srcs/sources_1/bd/radiation_system/ip/radiation_system_axi_gpio_0_0/radiation_system_axi_gpio_0_0.xci
# IP: The module: 'radiation_system_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Project/radiation_detection_pynq/radiation_detector/radiation_detector.gen/sources_1/bd/radiation_system/ip/radiation_system_axi_gpio_0_0/radiation_system_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'radiation_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/Project/radiation_detection_pynq/radiation_detector/radiation_detector.gen/sources_1/bd/radiation_system/ip/radiation_system_axi_gpio_0_0/radiation_system_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'radiation_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/Project/radiation_detection_pynq/radiation_detector/radiation_detector.gen/sources_1/bd/radiation_system/ip/radiation_system_axi_gpio_0_0/radiation_system_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'radiation_system_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
